### ISSUE TITLE
Dissociate website management from federation management

### ISSUE THREAD

**Issue by davidsandoz** [SwissTchoukball/website-v4#8]
More federation management is brought to the _administration_ of the website with more users connecting to it. Maybe it would be better to dissociate website management from federation management.

This would mean that only webpages textual content, translations and news would be kept in the website management in tchoukball.ch/admin. The rest could me moved to another interface, for instance to extranet.tchoukball.ch.

----

## Current situation
- Swiss Tchoukball website made in PHP which handles everything
- [Swiss Tchoukball API](/SwissTchoukball/api) made with the [Slim framework](/slimphp/Slim), which connects to the website DB to provide endpoints for the championship registration and team management for clubs.

## Goal
- **Swiss Tchoukball API** with own DB, containing all the federation data.
- **Swiss Tchoukball website** using the API to access the federation data.
- **Swiss Tchoukball Extranet** reading and writing the federation data through the API.

### Phase 1
- [ ] Set up the API MVP (see below)
- [ ] Create the Extranet MVP (see below)
- [ ] Prepare the current website to **read** the API

This phase can take as long as necessary.

### Phase 2
- [ ] Migrate data from current website DB to API DB
- [ ] Deploy the current website version with read-only access to API
- [ ] Inform users that they should now access the Extranet instead of the website

This phase should be as short as possible

### Phase 3
- [ ] Create the new website

### Technology
[Loopback 3](/strongloop/loopback) or even [Loopback 4](/strongloop/loopback-next) (expected for Q1 2019)

### MVP
- Members
  - Referees
  - National squad
  - Executive Committee
  - Commissions
  - Clubs
  - ... (anything related to members)
- Championship
- Swiss Cup
- Referee points and defrayal
- Venues
- Calendar

### Backlog
- Sponsors
- Press releases
- Tchoukup
- API access with tokens for clubs
- ...

### Technology
Custom [Angular](/angular/angular) SPA

### MVP
- User right management
- Members management for each club (as on the current website)
- Calendar management (as on the current website)
- Championship management (as on the current website)
- Referee points and defrayal management (as on the current website)
- Tchoukup distribution (as on the current website)
- Clubs statistics (as on the current website)

### Backlog
- Championship license administration
- National squad management
- Tchoukup management
- Swiss cup management
- More statistics (to develop...)

### Technology
A CMS, but which one?
CraftCMS ? Wagtail ? WordPress ? Concrete 5 ?

### Data left on the website database
(= Not accessed through the API)
- Website structure
- Text content
- News
- Downloads
